const accesToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI0ZmM0MzgxZC1lNzRkLTQ0MTAtYjBkZi1lMGY3YTU3OGNmNjkiLCJpZCI6MjQ1NDczLCJpYXQiOjE3Mjc4NTgyMDd9.JZGqwt9SJ82KlmejZW6nloj14cCdJaZuOobiFd7UH_A";
  export { accesToken};

